# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self  # Checkout des Codes aus dem Repository

- task: UseDotNet@2  # Installiere das .NET SDK
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Verwende das neueste .NET SDK

- task: DotNetCoreCLI@2  # Build und Tests durchf端hren
  displayName: 'Build and run tests'
  inputs:
    command: 'build'
    projects: '**/*.csproj'  # Alle .csproj-Dateien im Repository bauen

- task: DotNetCoreCLI@2  # Unit Tests ausf端hren
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: '**/*.csproj'  # F端hre Tests f端r alle Projekte aus
