trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  displayName: 'Login to Docker Registry'
  inputs:
    script: |
      docker login $(acr.host) -u $(acr.username) -p $(acr.password)

- task: CmdLine@2
  displayName: Build
  inputs:
    script: |
      docker run --privileged --rm tonistiigi/binfmt --install arm64
      docker run --privileged --rm tonistiigi/binfmt
      docker buildx create --use
      docker buildx build --platform linux/amd64,linux/arm64 \
        -t harbor.example.com/vecc/fileserver:$(build.buildNumber) \
        -t harbor.example.com/vecc/fileserver:latest \
        --push \
        .
